[package]
org = "gayaldassanayake"
name = "hospital_client"
version = "0.1.0"
distribution = "2201.9.1"

[[tool.openapi]]
id = "hospital-client"
filePath = "../resources/hospital_openapi.yaml"
options.mode = "client"
options.license = "../resources/mit-license.txt"

[[tool.openapi]]
id = "support-client"
filePath = "../resources/hospital_support_openapi.yaml"
targetModule = "support_client"
options.mode = "client"
